### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by hakkm** [blockchain-java-team/blockchain#3]

**Comment by hakkm** [comment]
Please add the class, and when you complete it, create an issue and assign it to me

**Comment by Adamo08** [comment]
> Please add the class, and when you complete it, create an issue and assign it to me

Added

**Comment by hakkm** [comment]
I commented on the PR for some small changes

**Comment by hakkm** [comment]
Can you remove the non relevant parts of our first version, like  attrs that ends with FX.
